services:
  fastapi-todo:
    build: .
    container_name: fastapi-todo
    ports:
      - "8000:8000"
    depends_on:
      - mongo-to-do
      - redis-to-do
    environment:
      - MONGO_DETAILS=mongodb://mongo-to-do:27017
      - SECRET_KEY=your_secret_key
    networks:
      - todo-network

  mongo-to-do:
    image: mongo:latest
    container_name: mongo-to-do
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - todo-network

  redis-to-do:
    image: redis:latest
    container_name: redis-to-do
    ports:
      - "6379:6379"
    networks:
      - todo-network

volumes:
  mongo-data:
    driver: local

networks:
  todo-network:
    external: true
